name: Test with Ubuntu, Miniconda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Install X system libraries for 3.7
      if: ${{ matrix.python-version == '3.7'}}
      run: |
        sudo apt-get update
        sudo apt-get install -y libxxf86vm1 libgtk2.0 libgtk2.0-dev
    - name: Set up Python from Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
    - name: Install conda dependencies
      run: |
        # printenv
        conda update -n base -c defaults conda
        conda config --set always_yes true --set changeps1 true
        conda config --add channels conda-forge
        conda install python=${{ matrix.python-version }}
        conda info -a
        conda install "numpy=>1.20" "scipy=>1.5" "matplotlib=>3.0" scikit-learn pandas
        conda install pyparsing pytest pytest-cov coverage
        conda install h5py pillow  sqlalchemy psutil pyyaml
        conda install psycopg2-binary numdifftools emcee
        #conda install tomopy
        conda install wxpython
        conda install pymatgen
        conda install cython
        conda info -a
        conda list
    - name: Install xraylarch and other dependencies with pip
      run: |
        pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils
        python setup.py install
    - name: Run test suite
      run: |
        git clone https://github.com/laumiulun/EXAFS-Neo-Public.git
        cd EXAFS-Neo-Public
        python setup.py install
        ./test
