name: Test with Windows, Miniconda

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10','3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python from Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: Install conda dependencies
      run: |
        printenv
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install mamba
        mamba install python=${{ matrix.python-version }}
        mamba install -y "numpy=>1.20" "scipy=>1.6" "matplotlib=>3.0" scikit-learn pandas
        mamba install -y -c conda-forge wxpython pymatgen tomopy pycifrw
        conda info -a
        conda list
    - name: Install xraylarch and other dependencies with pip
      run: |
        printenv
        pip install xraylarch
    - name: Run test suite
      run: |
        git clone https://github.com/laumiulun/EXAFS-Neo-Public.git
        cd EXAFS-Neo-Public
        python setup.py install
        python -m unittest discover -s tests -v
