name: Test with Ubuntu, Mamba

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python from Miniconda/mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
        python-version: ${{ matrix.python-version }}
    - name: Install mamba dependencies
      run: |
        printenv
        mamba install -y -c conda-forge python=${{ matrix.python-version }} numpy=>1.22 scipy=>1.8 matplotlib=>3.6 wxpython
        mamba install -y -c conda-forge scikit-image scikit-learn pycifrw pandas jupyter plotly pyparsing pytest pytest-cov coverage
    - name: Install xraylarch and other dependencies with pip
      run: |
        pip install lmfit peakutils pyepics pyshortcuts termcolor sphinx dill pycifrw xraydb wxmplot wxutils fabio silx imageio charset-normalizer
        pip install xraylarch
    - name: Run test suite
      run: |
        git clone https://github.com/laumiulun/EXAFS-Neo-Public.git
        cd EXAFS-Neo-Public
        python setup.py install
        python -m unittest discover -s tests -v
